### PR TITLE
faker gem added

### PR DESCRIPTION
**Pull request by MustafaAlomer711**
I added the faker gem and required the gem in seeds.rb file

### CODE REVIEW

**Review by abcattell91 — APPROVED** [review]
Looks good.

**Comment by MustafaAlomer711** [comment]
I also added basic creation of a boat in the seed file. please check this out. Is the docked: attribute meant to be a boolean because that will need to changed as its a string at the moment

**Comment by MustafaAlomer711** [comment]
The create, delete is working with the validation I added and shows up in our boats.

**Comment by abcattell91** [comment]
> I also added basic creation of a boat in the seed file. please check this out. Is the docked: attribute meant to be a boolean because that will need to changed as its a string at the moment

Yep should be a boolean. Should also do categories for boat in an array.  

Edit- can see them now! Brain not working 6am
/Not sure if you pushed git origin branchname for the changes after you did the seed file. Cant see the form and validation changes./

**Comment by abcattell91** [comment]
Think it all looks ok!

**Pull request merged**
